### ISSUE TITLE
Report a bug. "ffi" only has a single weight when connected together.

### ISSUE THREAD

**Issue by AzusaHana** [googlefonts/roboto-classic#104]
![Screenshot_2022-09-15-18-34-20-47_8d485484d290ec17555e7acc83d01a83](https://user-images.githubusercontent.com/100906636/190384522-894681d6-45ee-4995-b20b-23f749e0b77e.jpg)

**Comment by m4rc1e** [comment]
I'm not able to replicate this. 

What set of fonts are you using and what's the platform?

**Comment by AzusaHana** [comment]
> I'm not able to replicate this.
> 
> What set of fonts are you using and what's the platform?

Roboto_v3.005
OnePlus 8 Pro，Android 12 (OxygenOS)
I have this problem when I use this Roboto_v3.005 to make a magisk module.
Then I use the system Roboto font to replace, and there are multiple weights with the "ffi" displaying normally.
