### ISSUE TITLE
Shaping of the dot in the j caron dot below

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/roboto-classic#121]
The Samsung team reported that the input sequence: `ǰ̣` (U+01F0, U+0323) shapes with a collision of the dot below and tail of the `j`. This affects the Roboto fonts available on the Android system, and I can reproduce it in our current production Fonts version:

![7FCt2k7xMuseqWa](https://github.com/googlefonts/roboto-classic/assets/4249591/34c947a0-a164-48be-a0e8-2e8cf2c865b0)

---

b/341851281

**Comment by chrissimpkins** [comment]
@m4rc1e Have you had an opportunity to review this so that we can respond to Samsung?

**Comment by chrissimpkins** [comment]
Let's fix this in both variable and static font formats.  Thanks Marc!

**Comment by m4rc1e** [comment]
Hey Chris,

I've fixed the issue in #125 and cut a new release, https://github.com/googlefonts/roboto-classic/releases/tag/v3.010.

Please pass this along to the original issue authors.

**Comment by chrissimpkins** [comment]
Thank you very much Marc!
