### ISSUE TITLE
Missing cmap entries for superscript, subscript digits

### ISSUE THREAD

**Issue by davelab6** [googlefonts/roboto-classic#97]
B/213345773 was reported internally that Roboto is Missing cmap entries for superscript, subscript digits

**Comment by kpozin** [comment]
The `subs` and `sups` table entries are also missing for these glyphs; they're only present in `numr` and `dnom`.

**Comment by davelab6** [comment]
Thanks @kpozin :)

Full report

> Affected character(s): `U+2070, U+2071, U+2075–U+2079, U+2080–U+2089`
> 
> Roboto is missing cmap entries for most of the subscript and superscript digit code points.
> 
> Roboto does, however, have numr and dnom lookup tables that point to the required glyphs:
> 
> So the required glyphs exist in the font file, but they are only accessible through these lookup table, not directly by code point.
> 
> Please add cmap entries for these glyphs, and also add them to the subs and sups lookups.

**Comment by davelab6** [comment]
I've requested a review from @kpozin 's team :)

**Comment by kpozin** [comment]
The `cmap` changes look great, thanks!

It would be helpful to add `numr` and `dnom` tables, too, but that's less urgent.

**Comment by kpozin** [comment]
Sorry, that's `subs` and `sups`.

**Comment by davelab6** [comment]
@kpozin said,

> I apologize; I must have verified only the GitHub release files rather than the versions that got committed to the repo. The latest files at https://github.com/google/fonts/tree/main/apache/roboto (including the variable fonts) are in fact missing the cmap entries.
>
> It appears the web build doesn't currently include cmap entries for U+2070–U+2089, and that's likely the version that is checked into the repo. The other builds (android, chromeos, hinted, unhinted) all have them.

@m4rc1e i guess this is a bug in the build script?

**Comment by m4rc1e** [comment]
Ok, I've just seen that these glyphs are getting subsetted out of the webfonts. If I add them to the web subset list, https://github.com/googlefonts/roboto-classic/blob/master/scripts/web_subset.txt and regen, they're present. This is trivial to fix but it'll trigger the mac operations issue again. 

@kpozin do you specifically need the webfonts? It seems that many teams are using the webfonts without realising that the other sibling families may be better for them.

**Comment by kpozin** [comment]
We've been using the webfonts because the other variants are nearly three times as large, and some of our target devices are very space-constrained.

I'm going to try to use a local build for now, until the operations issue can be fixed.

**Comment by davelab6** [comment]
@m4rc1e what is the status of this?

**Comment by m4rc1e** [comment]
AFAIK, it's fixed. The family is currently in the [to_production list](https://github.com/google/fonts/pull/7345/files) so it should be landing soonish.

**Comment by davelab6** [comment]
That's OK, we have an issue in the main repo to track updating in the API; this repo issue tracker is scoped to the files in the repo, so, closing :)
